on:
  push:
    branches:
      - main

name: Release and publish NPM package
jobs:

  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: decentraland/gh-action-release@0.3.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: stub
    needs: release
    if: ${{ success() }}
    env:
      NODE_AUTH_TOKEN: stub
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: get latest release and export as GIT_TAG
        run:  echo "GIT_TAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -1)" > $GITHUB_ENV
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: install
        run:  yarn install --frozen-lockfile
      - name: check code lint
        run:  yarn lint:check
      - name: build
        run:  yarn build
      - name: api-extractor
        run:  yarn api-extractor-ci
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
