on:
  push:
    tags:
      - '*'
    branches:
      - main

name: Release and publish NPM package
jobs:

  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: decentraland/gh-action-release@0.3.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: stub
    needs: release
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
